### ISSUE TITLE
Demonios/servicios en Linux/Windows

### ISSUE THREAD

**Issue by dayer3** [madridpm/talks#1]
# Título
Demonios y servicios en Linux y Windows
# Descripción
Combinando algunas variables y la carga selectiva del módulo [Win32::Daemon](https://metacpan.org/pod/Win32::Daemon) podemos elaborar fácilmente un script que corra como servicio del sistema a la par que funcione tanto en Linux como en Windows.
# Bio del Ponente
Telemático e ingeniero de telecomunicación. Desde pequeño siempre me decían que me gustaban demasiado las teclas y los botones. Me gustan desde las redes y el desarrollo web hasta las fiestas populares de cuadrillas y participar en concursos de hacer migas, pasando por el tratamiento de imagen y sonido, la bici de montaña, el senderismo, los libros de aventuras, el cine clásico, el ferrocarril y la música electrónica.
# Nivel
Intermedio
# Duración
30-60 minutos

**Comment by pablrod** [comment]
Muchas gracias Juan! La programamos para el jueves 24 de noviembre.

He actualizado los detalles en [meetup](https://www.meetup.com/Madrid-Perl-Mongers/events/235150962/)

**Comment by pablrod** [comment]
El material de la presentación está en el repo: https://github.com/dayer3/perl-daemon-service

**Comment by dayer3** [comment]
Pablo si hay algún método github para asociar mi repo al de madrid.pm avisa.

2016-11-26 13:33 GMT+01:00 Pablo Rodríguez González <
notifications@github.com>:

**Comment by pablrod** [comment]
Transfiriendo la propiedad a la organización  @madridpm, o haciendo un fork desde @madridpm.
Con que esté en tu repo está perfecto (no borres el repo ;))
